#!/bin/bash

echo "" > POTFILES.skip
echo "" > POTFILES.in

cd ..

make distclean

cd src

rm *.c

cd ..

./autogen.sh $@

make

cd po

intltool-update -m 2> ./POTFILES.temp2
cat ./POTFILES.temp2 | grep /n | grep -v http | grep -v .in.in > ./POTFILES.temp
cat ./POTFILES.temp | grep -v .ui | grep -v .xml > POTFILES.skip
cat ./POTFILES.temp | grep -v .ui | sed 's/desktop\.in/desktop\.in\.in/' | sed 's/\.c/.vala/' > ./POTFILES.in
cat ./POTFILES.temp | grep .ui | awk '{ print "[type: gettext/glade]"$1 }' >> ./POTFILES.in
rm ./POTFILES.temp
rm ./POTFILES.temp2
